package com.example.smarttodolistapp;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Represents a single Task entity stored in the Room database.
 * Each task has an auto-generated ID, a title, and a completion status.
 */
@Entity(tableName = "tasks")
public class Task {

    // Unique ID for each task (automatically generated by Room)
    @PrimaryKey(autoGenerate = true)
    private int id;

    // The name or description of the task
    private String title;

    // Indicates whether the task has been completed
    private boolean completed;

    /**
     * Constructor used to create a new Task object.
     *
     * @param title     The title or text of the task
     * @param completed True if the task is completed, false otherwise
     */
    public Task(String title, boolean completed) {
        this.title = title;
        this.completed = completed;
    }

    // -------------------- Getters and Setters --------------------

    /**
     * Returns the unique ID of the task.
     * @return Task ID
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the task ID (used internally by Room).
     * @param id The new ID value
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Returns the title of the task.
     * @return Task title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Updates the title of the task.
     * @param title The new title value
     */
    public void setTitle(String title) {
        this.title = title;
    }

/**
 * Returns whether*/
 }